# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e78d82a22c3400d4588d910a971ef05d0d65b710d42710be1d5acb0afa56efb3501ff4a724463605d8dcaefc472d1ae9609e17ef185d784604a821682ea120f5

test:
  secret_key_base: aa3e3bbf0ebf56444646f1d98b2b8704bb20208f1bee2d13ae3cb5f4b514dbacef1c19565337e7d6cc53c592ca428442b8181fff53456c9a8d349c04546b43fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
